In [126]:
import numpy as np
import matplotlib.pyplot as plt

### Perceptron discreto

In [127]:
class PerceptronSimple:
    def __init__(self, input_size, output_size, lr=0.01, epochs=1000):
        self.w = np.random.randn(output_size, input_size)
        self.b = np.random.randn(output_size)
        self.lr = lr
        self.epochs = epochs

    def activation(self, x):
        return np.where(x >= 0, 1, 0)

    def predict(self, x_i):
        return self.activation(np.dot(self.w, x_i) + self.b)

    def train(self, X, d):
        for _ in range(self.epochs):
            for x_i, d_i in zip(X, d):
                d_pred = self.predict(x_i)
                error = d_i - d_pred
                self.w += self.lr * np.outer(error, x_i)
                self.b += self.lr * error

In [128]:
X = np.array([(0,0), (0,1), (1, 0), (1, 1)])
d = np.array([0, 0, 0, 1])

n = X.shape[1]

p = PerceptronSimple(n, 1)

p.train(X, d) 

p.predict((1,1))

array([1])

### Perceptron Grilla

In [129]:
def flatten(matrix):
    return np.array(matrix).flatten()

In [130]:
letras = {
    'A': flatten([
        [0,1,1,1,0],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1]
    ]),
    'B': flatten([
        [1,1,1,1,0],
        [1,0,0,0,1],
        [1,1,1,1,0],
        [1,0,0,0,1],
        [1,1,1,1,0]
    ]),
    'C': flatten([
        [0,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,0],
        [1,0,0,0,0],
        [0,1,1,1,1]
    ])
}

In [131]:
def letra_a_codigo(letra):
    index = ord(letra.upper()) - ord('A')
    return np.array([int(x) for x in format(index, '05b')])

print(letra_a_codigo('A')) # 0 0 0 0 0 = Letra 0
print(letra_a_codigo('B')) # 0 0 0 0 1 = Letra 1
print(letra_a_codigo('Z')) # 1 1 0 0 1 = Letra 25

[0 0 0 0 0]
[0 0 0 0 1]
[1 1 0 0 1]


In [132]:
X = []
d = []

for letra, grilla in letras.items():
    X.append(grilla)
    d.append(letra_a_codigo(letra))

X = np.array(X)
d = np.array(d)

n = X.shape[1]

p = PerceptronSimple(n, 5)

errs = p.train(X, d)

print(p.predict(letras['A']))
print(p.predict(letras['B']))
print(p.predict(letras['C']))
print(p.predict(flatten([ # R -> Deberia parecerse a B (0 0 0 0 1)
        [1,1,1,1,0],
        [1,0,0,0,1],
        [1,1,1,1,0],
        [1,0,0,1,0],
        [1,0,0,0,1]
    ])))
print(p.predict(flatten([ # G -> Deberia parecerse a C (0 0 0 1 0)
        [0,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,1,1],
        [1,0,0,0,1],
        [0,1,1,1,1]
    ])))

[0 0 0 0 0]
[0 0 0 0 1]
[0 0 0 1 0]
[0 0 0 0 1]
[0 0 0 1 0]
